# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u0417\u0430\u043f\u0438\u0441\u044c \u0441\u043e\u0437\u0434\u0430\u043d\u0430')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='\u0417\u0430\u043f\u0438\u0441\u044c \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0430')),
                ('developer', models.CharField(max_length=100, verbose_name='\u0420\u0430\u0437\u0440\u0430\u0431\u043e\u0442\u0447\u0438\u043a')),
                ('publisher', models.CharField(max_length=100, verbose_name='\u0418\u0437\u0434\u0430\u0442\u0435\u043b\u044c')),
                ('genre', models.CharField(max_length=100, verbose_name='\u0416\u0430\u043d\u0440')),
                ('sysreq', models.TextField(verbose_name='\u0421\u0438\u0441\u0442\u0435\u043c\u043d\u044b\u0435 \u0442\u0440\u0435\u0431\u043e\u0432\u0430\u043d\u0438\u044f')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
            ],
            options={
                'ordering': ['game'],
                'verbose_name': '\u0434\u0435\u043c\u043e\u0432\u0435\u0440\u0441\u0438\u044f',
                'verbose_name_plural': '\u0434\u0435\u043c\u043e\u0432\u0435\u0440\u0441\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='DemoImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u0417\u0430\u043f\u0438\u0441\u044c \u0441\u043e\u0437\u0434\u0430\u043d\u0430')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='\u0417\u0430\u043f\u0438\u0441\u044c \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0430')),
                ('image', models.ImageField(upload_to='magazine/demo', verbose_name='\u0421\u043a\u0440\u0438\u043d')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datafill.Demo', verbose_name='\u0414\u0435\u043c\u043e\u0432\u0435\u0440\u0441\u0438\u044f')),
            ],
            options={
                'ordering': ['game'],
                'verbose_name': '\u0441\u043a\u0440\u0438\u043d \u0434\u0435\u043c\u043e\u0432\u0435\u0440\u0441\u0438\u0438',
                'verbose_name_plural': '\u0441\u043a\u0440\u0438\u043d\u044b \u0434\u0435\u043c\u043e\u0432\u0435\u0440\u0441\u0438\u0439',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u0417\u0430\u043f\u0438\u0441\u044c \u0441\u043e\u0437\u0434\u0430\u043d\u0430')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='\u0417\u0430\u043f\u0438\u0441\u044c \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0430')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': '\u0418\u0433\u0440\u0430',
                'verbose_name_plural': '\u0418\u0433\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u0417\u0430\u043f\u0438\u0441\u044c \u0441\u043e\u0437\u0434\u0430\u043d\u0430')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='\u0417\u0430\u043f\u0438\u0441\u044c \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0430')),
                ('title', models.CharField(choices=[('IM', '\u0418\u0433\u0440\u043e\u043c\u0430\u043d\u0438\u044f')], default='IM', max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('number', models.PositiveSmallIntegerField(verbose_name='\u041d\u043e\u043c\u0435\u0440')),
                ('public_year', models.PositiveSmallIntegerField(choices=[(1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)], default=2016, verbose_name='\u0413\u043e\u0434 \u0432\u044b\u0445\u043e\u0434\u0430')),
                ('public_month', models.PositiveSmallIntegerField(choices=[(1, '\u042f\u043d\u0432\u0430\u0440\u044c'), (2, '\u0424\u0435\u0432\u0440\u0430\u043b\u044c'), (3, '\u041c\u0430\u0440\u0442'), (4, '\u0410\u043f\u0440\u0435\u043b\u044c'), (5, '\u041c\u0430\u0439'), (6, '\u0418\u044e\u043d\u044c'), (7, '\u0418\u044e\u043b\u044c'), (8, '\u0410\u0432\u0433\u0443\u0441\u0442'), (9, '\u0421\u0435\u043d\u0442\u044f\u0431\u0440\u044c'), (10, '\u041e\u043a\u0442\u044f\u0431\u0440\u044c'), (11, '\u041d\u043e\u044f\u0431\u0440\u044c'), (12, '\u0414\u0435\u043a\u0430\u0431\u0440\u044c')], default=3, verbose_name='\u041c\u0435\u0441\u044f\u0446 \u0432\u044b\u0445\u043e\u0434\u0430')),
                ('cover', models.ImageField(upload_to='magazine/cover', verbose_name='\u041e\u0431\u043b\u043e\u0436\u043a\u0430')),
            ],
            options={
                'verbose_name': '\u0416\u0443\u0440\u043d\u0430\u043b',
                'verbose_name_plural': '\u0416\u0443\u0440\u043d\u0430\u043b\u044b',
            },
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u0417\u0430\u043f\u0438\u0441\u044c \u0441\u043e\u0437\u0434\u0430\u043d\u0430')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='\u0417\u0430\u043f\u0438\u0441\u044c \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0430')),
                ('version', models.CharField(max_length=10, verbose_name='\u0412\u0435\u0440\u0441\u0438\u044f')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datafill.Game', verbose_name='\u0418\u0433\u0440\u0430')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datafill.Magazine', verbose_name='\u0416\u0443\u0440\u043d\u0430\u043b')),
            ],
            options={
                'ordering': ['game'],
                'verbose_name': '\u041f\u0430\u0442\u0447',
                'verbose_name_plural': '\u041f\u0430\u0442\u0447\u0438',
            },
        ),
        migrations.AlterUniqueTogether(
            name='magazine',
            unique_together=set([('title', 'number'), ('public_year', 'public_month')]),
        ),
        migrations.AddField(
            model_name='demo',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datafill.Game', verbose_name='\u0418\u0433\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='demo',
            name='magazine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datafill.Magazine', verbose_name='\u0416\u0443\u0440\u043d\u0430\u043b'),
        ),
    ]
